on:
  schedule: [{ cron: "30 1 * * *" }] # Schedule to run the workflow every day at 1:30 AM
  workflow_dispatch:
env:
  github_org: xtclang
jobs:
  clean:
    if: ${{ false }}
    name: Delete Expired Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Code
        uses: actions/checkout@v2
      - name: Run Delete Script
        # run: sh ./delete.sh (your org or github name) (your repo name)
        run: sh ./delete.sh ${ env.github_org }} github-test-action
        working-directory: .github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
